# ./netlify.toml 

[functions]  
  node_bundler = "esbuild"  
  ignored_node_modules = ["ky-universal"]
  external_node_modules = ["jsdom"]


[functions."cron"]
  schedule = "*/15 15,16,17 * * *"

# above cron is utc equivalent to ist "*/15 21,22,23 * * *"